ARG version
FROM almalinux:${version:-9}
ARG cousre= "aws devops"\
    duration= "120 hours"\
ENV duration=$duration
RUN echo "cousre: $course, duration: $duration, version: $version"
CMD ["sleep", "100"]
